import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

// supabase-js also sends x-client-info and apikey; they must be allowed or the browser
// blocks the request at the CORS preflight.
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const esc = (str: unknown): string =>
    String(str ?? "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");

  const { structured_data: d, patient: p } = await req.json();

  const fmt = (arr) =>
    arr?.length > 0
      ? arr.map((x) => `<li>${esc(x)}</li>`).join("")
      : "<li>None recorded</li>";

  const fmtMeds = (arr) =>
    arr?.length > 0
      ? arr
          .map(
            (m) =>
              `<li><strong>${esc(m.name || "Unknown")}</strong>${m.dosage ? ` — ${esc(m.dosage)}` : ""}${m.frequency ? `, ${esc(m.frequency)}` : ""}</li>`
          )
          .join("")
      : "<li>None recorded</li>";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>CareConnect Discharge Summary</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Fraunces:ital,wght@1,600&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Inter', sans-serif; color: #1A2332; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-family: 'Fraunces', serif; font-style: italic; font-size: 28px; color: #4A9B8E; margin-bottom: 4px; }
    .subtitle { color: #9CA3AF; font-size: 13px; margin-bottom: 32px; }
    .patient-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 24px; background: #F4F1EE; border-radius: 12px; padding: 20px; margin-bottom: 28px; }
    .patient-grid div { font-size: 14px; }
    .patient-grid span { color: #9CA3AF; display: block; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
    section { margin-bottom: 24px; }
    section h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.8px; color: #4A9B8E; border-bottom: 1.5px solid #E8E4DF; padding-bottom: 6px; margin-bottom: 12px; }
    ul { padding-left: 18px; }
    li { font-size: 14px; line-height: 1.8; color: #4A5568; }
    .footer { margin-top: 48px; font-size: 11px; color: #9CA3AF; border-top: 1px solid #E8E4DF; padding-top: 12px; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <h1>CareConnect</h1>
  <div class="subtitle">Discharge Summary — Generated ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</div>

  <div class="patient-grid">
    <div><span>Patient Name</span>${esc(p?.name || d?.patient_name || "Unknown")}</div>
    <div><span>Age</span>${esc(p?.age || "—")}</div>
    <div><span>Discharge Date</span>${esc(p?.discharge_date || "—")}</div>
    <div><span>Condition Severity</span>${p?.condition_severity ? `${esc(p.condition_severity)}/5` : "—"}</div>
  </div>

  <section>
    <h2>Diagnosis</h2>
    <ul>${fmt(d?.diagnosis)}</ul>
  </section>

  <section>
    <h2>Medications</h2>
    <ul>${fmtMeds(d?.medications)}</ul>
  </section>

  <section>
    <h2>Follow-up Instructions</h2>
    <ul>${fmt(d?.follow_ups)}</ul>
  </section>

  <section>
    <h2>Warning Signs to Watch For</h2>
    <ul>${fmt(d?.warning_signs)}</ul>
  </section>

  <section>
    <h2>Dietary Guidelines</h2>
    <ul>${fmt(d?.diet)}</ul>
  </section>

  <section>
    <h2>Activity Restrictions</h2>
    <ul>${fmt(d?.activity_restrictions)}</ul>
  </section>

  <div class="footer">
    Generated by CareConnect · This document is for personal health reference only.
    Always follow your doctor's advice.
  </div>
</body>
</html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html",
      ...corsHeaders,
    },
  });
});
